GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJzdWIiOjEsImlhdCI6MTc2ODg1NTY3NywiZXhwIjoxNzY4ODU1NzM3fQ.YXY-3CnMruyLqsgmwX4vROhXkjw7NjaqKzqMImU5Fe4